global:
  debug: True
  cfg_transform: configs/detection/transform.yaml
  save_dir: static/assets/detections
  device: cuda:0 # [cpu, cuda:0]
  class_names:
    [
      "hot-dog",
      "Apple",
      "Artichoke",
      "Asparagus",
      "Bagel",
      "Baked-goods",
      "Banana",
      "Beer",
      "Bell-pepper",
      "Bread",
      "Broccoli",
      "Burrito",
      "Cabbage",
      "Cake",
      "Candy",
      "Cantaloupe",
      "Carrot",
      "Common-fig",
      "Cookie",
      "Dessert",
      "French-fries",
      "Grape",
      "Guacamole",
      "Hot-dog",
      "Ice-cream",
      "Muffin",
      "Orange",
      "Pancake",
      "Pear",
      "Popcorn",
      "Pretzel",
      "Strawberry",
      "Tomato",
      "Waffle",
      "food-drinks",
      "Cheese",
      "Cocktail",
      "Coffee",
      "Cooking-spray",
      "Crab",
      "Croissant",
      "Cucumber",
      "Doughnut",
      "Egg",
      "Fruit",
      "Grapefruit",
      "Hamburger",
      "Honeycomb",
      "Juice",
      "Lemon",
      "Lobster",
      "Mango",
      "Milk",
      "Mushroom",
      "Oyster",
      "Pasta",
      "Pastry",
      "Peach",
      "Pineapple",
      "Pizza",
      "Pomegranate",
      "Potato",
      "Pumpkin",
      "Radish",
      "Salad",
      "food",
      "Sandwich",
      "Shrimp",
      "Squash",
      "Squid",
      "Submarine-sandwich",
      "Sushi",
      "Taco",
      "Tart",
      "Tea",
      "Vegetable",
      "Watermelon",
      "Wine",
      "Winter-melon",
      "Zucchini",
      "Banh_mi",
      "Banh_trang_tron",
      "Banh_xeo",
      "Bun_bo_Hue",
      "Bun_dau",
      "Com_tam",
      "Goi_cuon",
      "Pho",
      "Hu_tieu",
      "Xoi",
    ]

model:
  name: YOLOv8
  args:
    max_det: 300 # # max detections per image limit, output of NMS, set <0 for default [effdet: 100; frcnn: 100; yolo: 1000]

data:
  dataloader:
    name: DataLoader
    args:
      batch_size: 1
      drop_last: False
      shuffle: False
