val:
  name: TVCompose
  args:
    transforms:
      - name: TVResize
        args:
          size: [256, 256]
      - name: TVToTensor
      - name: TVNormalize
        args:
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
